name: Insured Assurance 
run-name: Deploy with Maven
on: [push] 

jobs:
  deploy-with-maven: 
    runs-on: ubuntu-latest 
    steps: 
      - name: scp ssh pipelines
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          pass: ${{ secrets.PASS }}
          port: 22
          scp: |
            ./target/*.war => /tmp/
          last_ssh: |
            ls -lart /tmp

      - name: Invoke Jenkins Deployment Job
        uses: joshlk/jenkins-githubaction@master
        with:
            url: http://54.86.38.57:8080/
            job_name: GitHubActions_job
            username: admin
            api_token: ${{ secrets.JENKINS_TOKEN }}
            timeout: "1000"